version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3305:3304
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/animalbingo_app:delegated
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/animalbingo_app/node_modules:cached
      - /animalbingo_app/vendor
      - /animalbingo_app/tmp
      - /animalbingo_app/log
      - /animalbingo_app/.git
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4443/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 256m
    ports:
      - 4443:4443
volumes:
  mysql_data:
  bundle_data:
  node_modules: